# overlays/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base

# Include all patch files
patchesStrategicMerge:
  - patches/frontend-deployment.yaml
  - patches/backend-deployment.yaml
  - patches/backend-configmap.yaml
  - patches/ingress.yaml

# Secret generation
secretGenerator:
  - name: events-backend-secrets
    type: Opaque
    literals:
      - DB_PASSWORD=cG9zdGdyZXM=
      - MAIL_PASSWORD=VHR2ZlFsZjdVaENGZ0tYb05Kc0dA
      - AWS_ACCESS_KEY_ID=L3I2dS9vTGM5U0JTVlhZYm1Xc0xyU2xGT3BkRzlXMTF4MlN3Vno5aA==
      - AWS_SECRET_ACCESS_KEY=QUtJQVZDSUdPUDJYRFFPNkIyTTY=
