apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
bases:
  - ../../base
patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: aklilu13/habesha-hub:0.1.5
    target:
      kind: Deployment
      name: habesha-hub
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: habesha-hub.com
    target:
      kind: Ingress
      name: habesha-hub