# overlays/dev/patches/backend-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: events-backend-config
data:
  application.yaml: |
    spring:
      datasource:
        url: jdbc:postgresql://postgres-service.dev.svc.cluster.local:5432/events_db
        username: postgres
      jpa:
        hibernate:
          ddl-auto: update
      mail:
        host: smtp.mail.us-east-1.awsapps.com
        port: 465
        username: info@habesha-hub.com
        properties:
          mail:
            smtp:
              auth: true
              ssl:
                enable: true
              socketFactory:
                port: 465
                class: javax.net.ssl.SSLSocketFactory
    
    app:
      default:
        language: en
    
    logging:
      level:
        root: INFO
        com.habeshahub: DEBUG
        org.springframework.web: DEBUG
    
    aws:
      s3:
        region: eu-central-2
        bucket: habesha-hub-dev
        endpoint: https://s3.eu-central-2.amazonaws.com