apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: habesha-hub
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ethiopiandemena.com
      secretName: habesha-hub-tls
  rules:
    - host: ethiopiandemena.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: habesha-hub
                port:
                  number: 80