# base/events-backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-backend
  template:
    metadata:
      labels:
        app: events-backend
    spec:
      containers:
        - name: events-backend
          image: aklilu13/events-backend:base
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_CONFIG_LOCATION
              value: file:/config/application.yaml
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: events-backend-secrets
                  key: DB_PASSWORD
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: events-backend-config