# base/events-be-micros/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - secret.yaml
  - service.yaml

namePrefix: events-

commonLabels:
  app.kubernetes.io/component: backend
  app: events-backend