# base/events-backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: events-backend-service
spec:
  selector:
    app: events-backend
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP